import type { Metadata } from "next";
import "./globals.css";
import { Mali } from "next/font/google";
import { Providers } from "./providers";
import ThemeSwitch from "@/components/ThemeSwitch";

// Import font Mali
const mali = Mali({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Nam Tran Hoang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={mali.className} suppressHydrationWarning>
      <body>
        <Providers>
          <div className="p-4 border border-black">
            <ThemeSwitch />
          </div>
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
