import type { Metadata } from "next";
import "./globals.css";
import { Mali } from "next/font/google";
import ThemeToggle from "@/components/ThemeToggle";

// Import font Mali
const mali = Mali({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Nam Tran Hoang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={mali.className}>
      <body>
        <div>{children}</div>
      </body>
    </html>
  );
}
