import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Nam Tran Hoang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-mainBackground flex w-[60%] h-screen justify-center items-start mx-auto py-5">
        <div className="w-1/4 p-4 shadow-md font-semibold">
          <h2 className="text-whiteColor">Sidebar</h2>
        </div>
        <div className="w-2/3 p-4">{children}</div>
      </body>
    </html>
  );
}
