import type { Metadata } from "next";
import "./globals.css";
import { Mali } from "next/font/google";
import { Providers } from "../../providers";
import ThemeSwitch from "@/components/ThemeSwitch";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import LanguageSwitch from "@/components/LanguageSwitch";
import Siderbar from "@/components/Siderbar";

const mali = Mali({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Nam Tran Hoang",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale} className={mali.className} suppressHydrationWarning>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Providers>
            <div className="w-full flex h-screen bg-primary-color dark:bg-secondary-black ">
              <div className="w-[100%] lg:w-[65%] flex mx-auto">
                <div className="w-[30%] bg-main-black">
                  <Siderbar />
                </div>
                <div className="w-[70%] bg-primary-color dark:bg-secondary-black">
                  {children}
                </div>
              </div>
            </div>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
