import type { Metadata } from "next";
import "./globals.css";
import { Mali } from "next/font/google";
import { Providers } from "../../providers";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import LayoutContent from "@/components/LayoutContent";

const mali = Mali({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Nam Tran Hoang",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  const messages = await getMessages();

  return (
    <html lang={locale} className={mali.className} suppressHydrationWarning>
      <Providers>
        <NextIntlClientProvider messages={messages}>
          <body>
            <LayoutContent>{children}</LayoutContent>
          </body>
        </NextIntlClientProvider>
      </Providers>
    </html>
  );
}
