export const experiences = [
  {
    timePeriod: "9/2023 - 9/2024",
    position: "Full-stack Developer",
    company: "FPT Software",
    link: "https://www.linkedin.com/company/fpt-software",
    description: [
      "Developed and maintained internal company web applications to manage users and employees.",
      "Received, designed, and confirmed requirements before implement the features.",
      "Communicated, confirmed and integrated third-party APIs for various projects.",
      "Wrote guidelines for feature code and usage guide other project team members.",
      "Set up and managed CI/CD system based on project requirements.",
      "Handled system errors and managed server configurations.",
      "Using Jira for task management, tracking and managing personal tasks, and collaborating with the team to ensure timely delivery of features.",
    ],
    skills: [
      "TypeScript",
      "React.js",
      "ASP.NET",
      "Redux",
      "Ant Design",
      "SCSS",
      "mySQL",
      "AWS",
      "Azure",
      "Docker",
      "IIS",
      "Jira",
    ],
  },
  {
    timePeriod: "6/2023 - 8/2023",
    position: "Web Developer Intern",
    company: "FPT Innovation",
    link: "https://www.linkedin.com/company/fptsoftwareinnovation",
    description: [
      "Developed RESTful APIs using .NET Core.",
      "Implemented backend authentication and authorization with OAuth2.",
      "Built responsive UI components with React.js.",
      "Configure and deploy web application with Jenkins for CI/CD",
      "Worked as a developer in a Scrum team, participating in sprint planning, daily standups, and reviews to deliver features on time.",
    ],
    skills: ["TypeScript", "React.js", "ASP.NET", "mySQL", "Jenkins", "Azure"],
  },
];
